<a href="https://colab.research.google.com/github/kajose0/Data-Science/blob/main/Numpy_mini_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [1]:
data_file = "/content/drive/MyDrive/Colab Notebooks/makeSenseOfCensus.csv"

In [5]:
data = np.genfromtxt(data_file, delimiter=",", skip_header=1)
from google.colab import files
data_to_load = files.upload()

Saving makeSenseOfCensus.csv to makeSenseOfCensus.csv


In [6]:
import numpy as np


In [7]:
data_file="/content/makeSenseOfCensus.csv"
data = np.genfromtxt(data_file, delimiter=",", skip_header=1)
print("\nData:\n\n ", data)


Data:

  [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [8]:
print("\nType of data: \n\n\n", type(data))


Type of data: 


 <class 'numpy.ndarray'>


In [9]:
new_record=[[50, 9, 4, 1, 0, 0, 40, 0]]


In [11]:
data2=np.concatenate((data,new_record))
data2

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

In [12]:
age = data2[:,0]
age

array([39., 50., 38., ..., 40., 39., 50.])

In [13]:
max_age = max(age)
max_age

90.0

In [14]:
min_age = min(age)
min_age

17.0

In [15]:
age_mean = age.mean()
age_mean

38.06293706293706

In [16]:
age_std = age.std()
age_std

13.341478176165857

In [17]:
race_0 = data2[data2[:,2]==0]
race_1 = data2[data2[:,2]==1]
race_2 = data2[data2[:,2]==2]
race_3 = data2[data2[:,2]==3]
race_4 = data2[data2[:,2]==4]

In [18]:
len_0=len(race_0)
len_1=len(race_1)
len_2=len(race_2)
len_3=len(race_3)
len_4=len(race_4)

print(len_0, len_1, len_2, len_3, len_4)


10 27 110 6 848


In [19]:
minority_race = min(len_0, len_1, len_2, len_3, len_4)
print(minority_race)

6


In [20]:
if minority_race == len_0:
  minority_race = 0
elif minority_race == len_1:
  minority_race = 1
elif minority_race == len_2:
  minority_race = 2
elif minority_race == len_3:
  minority_race = 3
elif minority_race == len_4:
  minority_race = 4
print('Minority race: ',minority_race)

Minority race:  3


In [21]:
senior_citizens = data2[data2[:,0]>60]
senior_citizens


array([[7.9000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.7000e+01, 6.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+00, 0.0000e+00],
       [7.6000e+01, 1.4000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 1.0000e+00],
       [6.1000e+01, 9.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [7.0000e+01, 1.0000e+01, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        0.0000e+00, 4.0000e+01, 0.0000e+00],
       [6.4000e+01, 7.0000e+00, 4.0000e+00, 1.0000e+00, 0.0000e+00,
        2.1790e+03, 4.0000e+01, 0.0000e+00],
       [7.1000e+01, 1.0000e+01, 2.0000e+00, 1.0000e+00, 0.0000e+00,
        1.8160e+03, 2.0000e+00, 0.0000e+00],
       [6.8000e+01, 2.0000e+00, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+01, 0.0000e+00],
       [6.6000e+01, 1.1000e+01, 4.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 2.0000e+

In [22]:
working_hours_sum = sum(senior_citizens[:,6])
working_hours_sum

1917.0

In [23]:
senior_citizens_len = len(senior_citizens)
senior_citizens_len

61

In [24]:
avg_working_hours = working_hours_sum / senior_citizens_len
avg_working_hours

31.42622950819672

In [25]:
high = data2[data2[:,1]>10]
low = data2[data2[:,1]<=10]
print(high)
print(low)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [28. 13.  2. ...  0. 40.  0.]
 ...
 [45. 14.  4. ...  0. 45.  0.]
 [48. 13.  4. ...  0. 58.  1.]
 [39. 13.  4. ...  0. 50.  1.]]
[[38.  9.  4. ...  0. 40.  0.]
 [53.  7.  2. ...  0. 40.  0.]
 [49.  5.  2. ...  0. 16.  0.]
 ...
 [56.  9.  4. ...  0. 55.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [50.  9.  4. ...  0. 40.  0.]]


In [26]:
avg_pay_high = high[:,7].mean()
avg_pay_low = low[:,7].mean()
print(avg_pay_high)
print(avg_pay_low)


0.42813455657492355
0.13649851632047477
